version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
  open-pull-requests-limit: 10
  assignees:
    - "jennyEckstein"
    - "eaviles"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
  open-pull-requests-limit: 10
  assignees:
    - "jennyEckstein"
    - "eaviles"